### ISSUE TITLE
HumanGaitDataBase.zip downloading empty

### ISSUE THREAD

**Issue by lucasgaley** [romanchereshnev/HuGaDB#1]
Hello,

I've tried on a couple different computers now, but downloading the "HumanGaitDataBase.zip" file results in an unreadable 1 byte file. Would it be possible to re-upload the file?

Update:
Using GitHub desktop it says "This repository is over its data quota. Purchase more data packs to restore access." Is there another way to share this file?

Thanks so much for your good work on this project so far.

**Comment by romanchereshnev** [comment]
Hello Lucas. 

Unfortunately github has a limit on the number of downloads of large files.
But you can download it from [Dropbox ](https://www.dropbox.com/s/7nb9g650i5m9k6c/HuGaDB.zip?dl=0)or [Google Drive](https://drive.google.com/file/d/16Z4NYVo85-BcziIoBwgOCnHvUQ59F3Fo/view?pli=1) storages.

**Comment by lucasgaley** [comment]
Hello!

Thank you for your prompt reply and the links. I look forward to working with this dataset!
