### ISSUE TITLE
Doubt regarding Hz of sensors

### ISSUE THREAD

**Issue by ezetl** [romanchereshnev/HuGaDB#2]
Hello, I was reading the [paper](https://arxiv.org/pdf/1705.08506.pdf) and found that "The microcontroller collected 56.35 samples per second in average". Given that you had 38 signals to sample from all the sensors, does that mean that you have between 1 and 2 points per second per sensor/axis?

**Comment by romanchereshnev** [comment]
Hello, Ezequiel.
 
All 38 signals from sensors were being sent simultaneously. We got signals from all sensors 56.35 times per second.  Thus, there were collected around 56 points per second per each sensor/axis?

**Comment by ezetl** [comment]
Ok it is clear now, thank you!
