### ISSUE TITLE
Sampling rate of the dataset

### ISSUE THREAD

**Issue by mmalekzadeh** [romanchereshnev/HuGaDB#3]
Hi

Thanks for sharing this great dataset. I just had a quick question. 
What is the sampling rate of your data collection?
If we divide `Samples` by ` Time (s)`  we get something around 58.
Can we say your devices were collecting data in 58Hz?

Best
M.

**Comment by romanchereshnev** [comment]
Hello Mohammad,

The sampling rate of the device was 60 Hz. However, due to some problems the real sampling rate was around 58.8Hz on average.

**Comment by ocarbo** [comment]
> Hi
> 
> Thanks for sharing this great dataset. I just had a quick question. What is the sampling rate of your data collection? If we divide `Samples` by ` Time (s)` we get something around 58. Can we say your devices were collecting data in 58Hz?
> 
> Best M.

how did you find 58 hz ? what is sample ? what time ?
